In [1]:
import torch
from master_model import MasterModel
from ttokenizer import Tokenizer

u_tokenizer = Tokenizer("tokenizer.json")
prompt = "the capital of united states and the capital of france"
tokens = u_tokenizer.encode(prompt)

torch.manual_seed(1)
u_model = MasterModel(vocab_size=len(u_tokenizer.vocab), embedding_dim=4, context_length=32)

sentence_meanings = u_model(tokens)
sentence_meanings.shape

torch.Size([20, 4])

In [2]:
u_model(tokens)

tensor([[-1.5256, -0.7502, -0.6540, -1.6095],
        [-0.2323, -0.7360, -0.2287, -0.0216],
        [ 0.5956,  0.1624, -0.6406, -1.7717],
        [ 0.7659,  0.0950, -0.2198, -0.0666],
        [ 0.6953,  0.3404, -0.6180, -0.5343],
        [-0.4051,  0.6569, -0.2022, -0.1089],
        [ 0.2580,  1.6820, -0.0755,  0.5149],
        [-0.4287, -0.6418, -0.1765, -0.1469],
        [ 1.2498, -0.5207,  0.3446,  0.6405],
        [-0.0681, -0.3443,  1.6739, -0.1170],
        [ 0.5150,  0.5748, -0.1252, -0.1925],
        [ 0.2922,  0.1123, -0.0459, -0.1537],
        [-0.7370,  0.2291, -0.0845, -0.2136],
        [-1.0692, -1.3218,  1.3759, -1.0607],
        [ 0.0984, -0.7655, -0.0403, -0.2261],
        [ 0.4722,  0.3977,  1.5358, -1.0911],
        [ 0.6551,  0.4080,  0.0054, -0.2296],
        [ 0.4880,  0.6011,  0.3495, -0.7384],
        [-0.6436,  0.4259,  0.0509, -0.2240],
        [ 1.8689,  0.2104,  0.6809,  0.3993]], grad_fn=<CopySlices>)

In [3]:
u_tokenizer.tokenizer(prompt)

['the',
 ' ',
 'capital',
 ' ',
 'of',
 ' ',
 'united',
 ' ',
 'state',
 's',
 ' ',
 'and',
 ' ',
 'the',
 ' ',
 'capital',
 ' ',
 'of',
 ' ',
 'france']

In [4]:
from transformers import Gemma3ForCausalLM

gemma_model = Gemma3ForCausalLM.from_pretrained("google/gemma-3-1b-it")

/Users/gonul/llm-from-scratch/.llm_env/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 340/340 [00:00<00:00, 11120.96it/s]


In [5]:
u_model, gemma_model

(MasterModel(
   (embedding): Embedding(64, 4)
   (pos_embedding): Embedding(32, 4)
 ),
 Gemma3ForCausalLM(
   (model): Gemma3TextModel(
     (embed_tokens): Gemma3TextScaledWordEmbedding(262144, 1152, padding_idx=0)
     (layers): ModuleList(
       (0-25): 26 x Gemma3DecoderLayer(
         (self_attn): Gemma3Attention(
           (q_proj): Linear(in_features=1152, out_features=1024, bias=False)
           (k_proj): Linear(in_features=1152, out_features=256, bias=False)
           (v_proj): Linear(in_features=1152, out_features=256, bias=False)
           (o_proj): Linear(in_features=1024, out_features=1152, bias=False)
           (q_norm): Gemma3RMSNorm((256,), eps=1e-06)
           (k_norm): Gemma3RMSNorm((256,), eps=1e-06)
         )
         (mlp): Gemma3MLP(
           (gate_proj): Linear(in_features=1152, out_features=6912, bias=False)
           (up_proj): Linear(in_features=1152, out_features=6912, bias=False)
           (down_proj): Linear(in_features=6912, out_features=1152,

In [4]:
from plot_tokens import plot_dots
u_sentences = [
    {
        "words": sentence_meanings.detach().numpy(),
        "labels": u_tokenizer.tokenizer(prompt),
        "color": "red"
    }
]
plot_dots(u_sentences, "Models Context Space")

### Attention her bir tokenin diger tokenlarla iliskisi, önemi yakalamak cumle icinde

In [9]:
sentence_meanings

tensor([[-1.5256, -0.7502, -0.6540, -1.6095],
        [-0.2323, -0.7360, -0.2287, -0.0216],
        [ 0.5956,  0.1624, -0.6406, -1.7717],
        [ 0.7659,  0.0950, -0.2198, -0.0666],
        [ 0.6953,  0.3404, -0.6180, -0.5343],
        [-0.4051,  0.6569, -0.2022, -0.1089],
        [ 0.2580,  1.6820, -0.0755,  0.5149],
        [-0.4287, -0.6418, -0.1765, -0.1469],
        [ 1.2498, -0.5207,  0.3446,  0.6405],
        [-0.0681, -0.3443,  1.6739, -0.1170],
        [ 0.5150,  0.5748, -0.1252, -0.1925],
        [ 0.2922,  0.1123, -0.0459, -0.1537],
        [-0.7370,  0.2291, -0.0845, -0.2136],
        [-1.0692, -1.3218,  1.3759, -1.0607],
        [ 0.0984, -0.7655, -0.0403, -0.2261],
        [ 0.4722,  0.3977,  1.5358, -1.0911],
        [ 0.6551,  0.4080,  0.0054, -0.2296],
        [ 0.4880,  0.6011,  0.3495, -0.7384],
        [-0.6436,  0.4259,  0.0509, -0.2240],
        [ 1.8689,  0.2104,  0.6809,  0.3993]], grad_fn=<CopySlices>)

In [10]:
the_pos = [-1.5256, -0.7502, -0.6540, -1.6095]
capital_pos = [ 0.5956,  0.1624, -0.6406, -1.7717]
# distance between the_pos and capital_pos

#manhattan distance
hardness_dist = abs(the_pos[0] - capital_pos[0])
brightness_dist = abs(the_pos[1] - capital_pos[1])
redness_dist = abs(the_pos[2] - capital_pos[2])
blueness_dist = abs(the_pos[3] - capital_pos[3])

hardness_dist, brightness_dist, redness_dist, blueness_dist



(2.1212, 0.9126, 0.013400000000000079, 0.16220000000000012)

In [11]:
total_dist = hardness_dist + brightness_dist + redness_dist + blueness_dist
total_dist

3.2094000000000005

In [12]:
#gemma 1152 eksen bi kelimeye incelenir, 
#cosinus benzerligi
#cos_sim = np.dot(the_pos, capital_pos)/(np.linalg.norm(the_pos)*np.linalg.norm(capital_pos))
cos_sim_hardness = the_pos[0] * capital_pos[0]
cos_sim_brightness = the_pos[1] * capital_pos[1]
cos_sim_redness = the_pos[2] * capital_pos[2]
cos_sim_blueness = the_pos[3] * capital_pos[3]
total_cos_sim = the_pos[0] * capital_pos[0] + the_pos[1] * capital_pos[1] + the_pos[2] * capital_pos[2] + the_pos[3] * capital_pos[3]
cos_sim_hardness, cos_sim_brightness, cos_sim_redness, cos_sim_blueness, total_cos_sim

(-0.90864736, -0.12183247999999999, 0.4189524, 2.85155115, 2.24002371)

$$
\text{Attention}(Q, K, V) = \text{softmax}\left(\frac{QK^{\top}}{\sqrt{d_k}}\right)V
$$

$$
Q = \text{Query (Sorgu)}
$$

$$
K = \text{Key (Anahtar)}
$$

$$
V = \text{Value (İçerik)}
$$

$$
QK^{\top} \rightarrow \text{Similarity (benzerlik)}
$$

$$
\sqrt{d_k} \rightarrow \text{Scaling (sayilar cok buyumesin)}
$$

$$
\text{softmax}(\cdot) \rightarrow \text{Attention weights}
$$

$$
\text{weights} \times V \rightarrow \text{Weighted sum}
$$

$$
d_k = \text{Key vektörünün boyutu}
$$

$$
\text{embedding\_dim} = 512
$$

$$
\text{heads} = 8
$$

$$
d_k = \frac{512}{8} = 64
$$

$$
\text{Neden } \sqrt{d_k} \text{ var?}
$$

$$
\text{Dot product büyür, softmax saturate olur (çok keskin olur).}
$$

$$
\text{Scale} = \frac{1}{\sqrt{d_k}}
$$

In [17]:
cs_0_0 = sentence_meanings[0][0] * sentence_meanings[0][0] + sentence_meanings[0][1] * sentence_meanings[0][1] + sentence_meanings[0][2] * sentence_meanings[0][2] + sentence_meanings[0][3] * sentence_meanings[0][3]
cs_0_1 = sentence_meanings[0][0] * sentence_meanings[1][0] + sentence_meanings[0][1] * sentence_meanings[1][1] + sentence_meanings[0][2] * sentence_meanings[1][2] + sentence_meanings[0][3] * sentence_meanings[1][3]
cs_0_2 = sentence_meanings[0][0] * sentence_meanings[2][0] + sentence_meanings[0][1] * sentence_meanings[2][1] + sentence_meanings[0][2] * sentence_meanings[2][2] + sentence_meanings[0][3] * sentence_meanings[2][3]
cs_0_3 = sentence_meanings[0][0] * sentence_meanings[3][0] + sentence_meanings[0][1] * sentence_meanings[3][1] + sentence_meanings[0][2] * sentence_meanings[3][2] + sentence_meanings[0][3] * sentence_meanings[3][3]
cs_0_0, cs_0_1, cs_0_2, cs_0_3

(tensor(5.9084, grad_fn=<AddBackward0>),
 tensor(1.0909, grad_fn=<AddBackward0>),
 tensor(2.2399, grad_fn=<AddBackward0>),
 tensor(-0.9888, grad_fn=<AddBackward0>))

In [20]:
the_similarities = []
for i in range(sentence_meanings.shape[0]):
    cs_the_i = sentence_meanings[0][0] * sentence_meanings[i][0] + sentence_meanings[0][1] * sentence_meanings[i][1] + sentence_meanings[0][2] * sentence_meanings[i][2] + sentence_meanings[0][3] * sentence_meanings[i][3]
    the_similarities.append(cs_the_i)
the_similarities

[tensor(5.9084, grad_fn=<AddBackward0>),
 tensor(1.0909, grad_fn=<AddBackward0>),
 tensor(2.2399, grad_fn=<AddBackward0>),
 tensor(-0.9888, grad_fn=<AddBackward0>),
 tensor(-0.0521, grad_fn=<AddBackward0>),
 tensor(0.4328, grad_fn=<AddBackward0>),
 tensor(-2.4349, grad_fn=<AddBackward0>),
 tensor(1.4875, grad_fn=<AddBackward0>),
 tensor(-2.7723, grad_fn=<AddBackward0>),
 tensor(-0.5442, grad_fn=<AddBackward0>),
 tensor(-0.8252, grad_fn=<AddBackward0>),
 tensor(-0.2526, grad_fn=<AddBackward0>),
 tensor(1.3515, grad_fn=<AddBackward0>),
 tensor(3.4301, grad_fn=<AddBackward0>),
 tensor(0.8144, grad_fn=<AddBackward0>),
 tensor(-0.2670, grad_fn=<AddBackward0>),
 tensor(-0.9395, grad_fn=<AddBackward0>),
 tensor(-0.2354, grad_fn=<AddBackward0>),
 tensor(0.9896, grad_fn=<AddBackward0>),
 tensor(-4.0971, grad_fn=<AddBackward0>)]

In [23]:
all_similarities = torch.zeros(sentence_meanings.shape[0], sentence_meanings.shape[0])
for j in range(sentence_meanings.shape[0]):
    j_similarities = torch.zeros(sentence_meanings.shape[0])

    for i in range(sentence_meanings.shape[0]):
        for k in range(sentence_meanings.shape[1]):
            cs_j_i = sentence_meanings[j][k] * sentence_meanings[i][k]
            j_similarities[i] += cs_j_i

    all_similarities[j] = j_similarities

all_similarities.detach().numpy()

array([[ 5.90842342e+00,  1.09090900e+00,  2.23986316e+00,
        -9.88827467e-01, -5.20781875e-02,  4.32813108e-01,
        -2.43488336e+00,  1.48745728e+00, -2.77234793e+00,
        -5.44172764e-01, -8.25160801e-01, -2.52631605e-01,
         1.35150814e+00,  3.43013191e+00,  8.14448595e-01,
        -2.66969919e-01, -9.39509153e-01, -2.35441327e-01,
         9.89629149e-01, -4.09709406e+00],
       [ 1.09090900e+00,  6.48404419e-01, -7.31844902e-02,
        -1.96182489e-01, -2.59241372e-01, -3.40761095e-01,
        -1.29174280e+00,  6.15466297e-01,  2.09216960e-04,
        -1.11021109e-01, -5.09930313e-01, -1.36732802e-01,
         2.65630167e-02,  9.29542363e-01,  5.54635823e-01,
        -7.29970038e-01, -4.48780864e-01, -6.19718373e-01,
        -1.70698896e-01, -7.53346860e-01],
       [ 2.23986316e+00, -7.31844902e-02,  3.93028903e+00,
         7.30418503e-01,  1.81196070e+00,  1.87916636e-01,
        -4.37046915e-01,  1.38006508e-02, -6.95667922e-01,
        -9.61368263e-01,  8.2

In [25]:
# Query, Key, Value
# Query, Key
all_sim_torch = sentence_meanings @ sentence_meanings.T #her bi token diger tokena ne kadar benziyor.
all_sim_torch.detach().numpy()

array([[ 5.90842342e+00,  1.09090900e+00,  2.23986316e+00,
        -9.88827467e-01, -5.20781577e-02,  4.32813108e-01,
        -2.43488336e+00,  1.48745728e+00, -2.77234793e+00,
        -5.44172704e-01, -8.25160801e-01, -2.52631605e-01,
         1.35150814e+00,  3.43013191e+00,  8.14448595e-01,
        -2.66969949e-01, -9.39509213e-01, -2.35441372e-01,
         9.89629149e-01, -4.09709406e+00],
       [ 1.09090900e+00,  6.48404419e-01, -7.31844753e-02,
        -1.96182489e-01, -2.59241372e-01, -3.40761125e-01,
        -1.29174280e+00,  6.15466297e-01,  2.09224876e-04,
        -1.11021116e-01, -5.09930313e-01, -1.36732817e-01,
         2.65630204e-02,  9.29542363e-01,  5.54635823e-01,
        -7.29970038e-01, -4.48780864e-01, -6.19718373e-01,
        -1.70698896e-01, -7.53346860e-01],
       [ 2.23986316e+00, -7.31844753e-02,  3.93028903e+00,
         7.30418503e-01,  1.81196058e+00,  1.87916622e-01,
        -4.37046945e-01,  1.38006508e-02, -6.95667982e-01,
        -9.61368263e-01,  8.2

In [26]:
# scaling
#attention_weights = all_similarities/torch.sum(all_similarities, dim=1, keepdim=True)
attention_weights = torch.softmax(all_similarities,dim=1)
attention_weights

tensor([[8.5336e-01, 6.9010e-03, 2.1772e-02, 8.6237e-04, 2.2005e-03, 3.5736e-03,
         2.0309e-04, 1.0260e-02, 1.4492e-04, 1.3453e-03, 1.0157e-03, 1.8006e-03,
         8.9555e-03, 7.1585e-02, 5.2342e-03, 1.7750e-03, 9.0597e-04, 1.8318e-03,
         6.2363e-03, 3.8529e-05],
        [1.3599e-01, 8.7365e-02, 4.2458e-02, 3.7544e-02, 3.5250e-02, 3.2490e-02,
         1.2553e-02, 8.4535e-02, 4.5691e-02, 4.0881e-02, 2.7433e-02, 3.9844e-02,
         4.6911e-02, 1.1573e-01, 7.9546e-02, 2.2015e-02, 2.9163e-02, 2.4581e-02,
         3.8513e-02, 2.1506e-02],
        [1.0082e-01, 9.9772e-03, 5.4663e-01, 2.2285e-02, 6.5723e-02, 1.2954e-02,
         6.9340e-03, 1.0884e-02, 5.3539e-03, 4.1046e-03, 2.4408e-02, 1.7594e-02,
         1.1070e-02, 1.2426e-02, 1.5397e-02, 3.9203e-02, 2.5363e-02, 4.6812e-02,
         1.1285e-02, 1.0774e-02],
        [1.4034e-02, 3.1004e-02, 7.8313e-02, 7.2147e-02, 7.8779e-02, 3.1004e-02,
         5.2986e-02, 2.6830e-02, 8.3070e-02, 2.4175e-02, 6.1541e-02, 4.8674e-02,
       

In [27]:
torch.sum(attention_weights[0])

tensor(1.0000, grad_fn=<SumBackward0>)

In [29]:
# her bir tokenin cumle icindeki anlami
sentence_context_vector =  attention_weights @ sentence_meanings # Value
sentence_context_vector, sentence_meanings

(tensor([[-1.3772, -0.7363, -0.4744, -1.4997],
         [-0.2089, -0.3200,  0.1015, -0.5134],
         [ 0.2991,  0.0908, -0.3639, -1.2718],
         [ 0.5683,  0.1713,  0.1052, -0.2392],
         [ 0.4428,  0.2287, -0.0983, -0.5265],
         [ 0.0088,  0.2746,  0.0068, -0.3576],
         [ 0.3462,  1.0018,  0.0150,  0.1387],
         [-0.3609, -0.3635,  0.1034, -0.6210],
         [ 1.0690, -0.0208,  0.4075,  0.1717],
         [-0.1347, -0.3926,  1.1744, -0.5724],
         [ 0.4459,  0.3187,  0.0870, -0.2984],
         [ 0.3038,  0.1255,  0.1256, -0.3465],
         [-0.3086, -0.0650,  0.0406, -0.5655],
         [-0.9862, -1.1603,  1.1931, -1.0279],
         [-0.0440, -0.2799,  0.1951, -0.4897],
         [ 0.2940,  0.1143,  1.1035, -0.7629],
         [ 0.5145,  0.2558,  0.1521, -0.3000],
         [ 0.3976,  0.2583,  0.2898, -0.5347],
         [-0.1837,  0.0563,  0.0966, -0.4916],
         [ 1.3830,  0.1471,  0.5318,  0.2190]], grad_fn=<MmBackward0>),
 tensor([[-1.5256, -0.7502, -0.6540

In [31]:
attention_sentence = [
    {
        "words": sentence_context_vector.detach().numpy(),
        "labels": u_tokenizer.tokenizer(prompt),
        "color": "red"
    },
    {
        "words": sentence_meanings.detach().numpy(),
        "labels": u_tokenizer.tokenizer(prompt),
        "color": "blue"
    }
]
plot_dots(attention_sentence, "Models Attention Sentence Space")

In [32]:
sentence_meanings_without_pos = u_model.embedding(tokens)

In [33]:
attention_sentence = [
    {
        "words": sentence_context_vector.detach().numpy(),
        "labels": u_tokenizer.tokenizer(prompt),
        "color": "red"
    },
    {
        "words": sentence_meanings.detach().numpy(),
        "labels": u_tokenizer.tokenizer(prompt),
        "color": "blue"
    },
     {
        "words": sentence_meanings_without_pos.detach().numpy(),
        "labels": u_tokenizer.tokenizer(prompt),
        "color": "green"
    }
]
plot_dots(attention_sentence, "Models Attention Sentence Space")