In [1]:
#the capital of france is paris
prompt = "the capital of the united states"
next_token = "paris" # modelin ciktisi degil
output = "the capital of france is paris"



In [2]:
context_length = 12 #gpt-4o 128k, gemma-3- model 12 bin alirsa 12 bin uretir. metni 12bin parcalarina bolmek gerek. son 12 bin olmaz ise padding token ekler.
# model context_length islenecek token modeldeki, olusturulan output token bi token kaydirarak output olusturur.
ornek_input_data = "the capital <pad> <pad> <pad> <pad>"
ornek_hedef = "capital of <pad> <pad> <pad> <pad> "

In [3]:

import json
with open("tokenizer.json", "r") as f:
    vocab = json.load(f)

In [4]:
vocab

{'the': 0,
 'capital': 1,
 'of': 2,
 'united': 3,
 'state': 4,
 'is': 5,
 'not': 6,
 'london': 7,
 'france': 8,
 'paris': 9,
 'and': 10,
 'berlin': 11,
 'germany': 12,
 'rome': 13,
 'in': 14,
 'italy': 15,
 'madrid': 16,
 'spain': 17,
 'lisbon': 18,
 'portugal': 19,
 'kingdom': 20,
 'washington': 21,
 'although': 22,
 'these': 23,
 'place': 24,
 'are': 25,
 'often': 26,
 'mention': 27,
 'together': 28,
 'each': 29,
 'country': 30,
 'has': 31,
 'its': 32,
 'own': 33,
 'identity': 34,
 'any': 35,
 'european': 36,
 'city': 37,
 'remain': 38,
 'important': 39,
 'with': 40,
 'a': 41,
 'rich': 42,
 'history': 43,
 'culture': 44,
 'europe': 45,
 'made': 46,
 'many': 47,
 'unique': 48,
 'world': 49,
 'while': 50,
 'known': 51,
 'for': 52,
 'art': 53,
 'fashion': 54,
 'famous': 55,
 'they': 56,
 'ed': 57,
 's': 58,
 '.': 59,
 ',': 60,
 ' ': 61,
 '<unk>': 62,
 '<pad>': 63}

In [5]:
#from tokenizers import Tokenizer
#from tokenizers.models import WordLevel
#from tokenizers.pre_tokenizers import Whitespace, Split

#model = WordLevel(
#    vocab=vocab,
#    unk_token="<unk>"
#)
#tokenizer = Tokenizer(model) #Byte Pair Encoding BPE
#tokenizer.pre_tokenizer = Whitespace()

#tokenizer.pre_tokenizer = Split(
#    pattern=" ",
#    behavior="isolated"
#)

#ids = tokenizer.encode(prompt)
#ids.ids, tokenizer.decode(ids.ids)

In [6]:
from ttokenizer import Tokenizer

tokenizer = Tokenizer("tokenizer.json")

ids = tokenizer.encode(prompt)

len(ids), ids

(12, [0, 61, 1, 61, 2, 61, 0, 61, 3, 61, 4, 58])

In [7]:
prompt

'the capital of the united states'

In [8]:
print(tokenizer.decode(ids))

the capital of the united states


In [9]:
data = "the capital of france is paris,"
hedef = " capital of france is paris, "

In [10]:
ids = tokenizer.encode(data)
print(len(ids))

12


In [11]:
#from transformers import AutoTokenizer, AutoModelForCausalLM, Gemma3ForCausalLM

#tokenizer = AutoTokenizer.from_pretrained("google/gemma-3-1b-it")
#model = AutoModelForCausalLM.from_pretrained("google/gemma-3-1b-it") # modeli uygula komple model iniyor, context_length ogrenmek icin 
#it instruct-tuned, insan komutlarını takip edecek şekilde fine-tune edilmiş versiyon
#model = Gemma3ForCausalLM.from_pretrained("google/gemma-3-1b-it")

In [12]:
girdi = "the letter capital of the united states is not"
cikti = "letter capital of the united states is not london"

In [13]:
with open("text.txt", "r") as f:
    text = f.read()
text

'the capital of the united states is not london. the capital of france is paris, and berlin is the capital of germany. rome is in italy, \n\nmadrid is in spain, and lisbon is in portugal. the capital of the united kingdom is not paris, and the capital of the united states is not berlin. \nalthough these places are often mentioned together, although these capitals are often mentioned together, although these are often mentioned together, \neach country has its own capital, and each country has its own city, and each capital has its own identity, and each capital has its own history. washington \nis the capital of the united states, and london is the capital of the united kingdom. paris is known for art and fashion, and berlin is known for art and \nhistory, and rome is known for art and history, and madrid is known for culture and history, and lisbon is known for culture and art. rome is rich with culture, \nrome is rich with history, rome is rich with art, and madrid is rich with art a

In [14]:
token_ids = tokenizer.encode(text)
print(token_ids)

[0, 61, 1, 61, 2, 61, 0, 61, 3, 61, 4, 58, 61, 5, 61, 6, 61, 7, 59, 61, 0, 61, 1, 61, 2, 61, 8, 61, 5, 61, 9, 60, 61, 10, 61, 11, 61, 5, 61, 0, 61, 1, 61, 2, 61, 12, 59, 61, 13, 61, 5, 61, 14, 61, 15, 60, 61, 16, 61, 5, 61, 14, 61, 17, 60, 61, 10, 61, 18, 61, 5, 61, 14, 61, 19, 59, 61, 0, 61, 1, 61, 2, 61, 0, 61, 3, 61, 20, 61, 5, 61, 6, 61, 9, 60, 61, 10, 61, 0, 61, 1, 61, 2, 61, 0, 61, 3, 61, 4, 58, 61, 5, 61, 6, 61, 11, 59, 61, 22, 61, 23, 61, 24, 58, 61, 25, 61, 26, 61, 27, 57, 61, 28, 60, 61, 22, 61, 23, 61, 1, 58, 61, 25, 61, 26, 61, 27, 57, 61, 28, 60, 61, 22, 61, 23, 61, 25, 61, 26, 61, 27, 57, 61, 28, 60, 61, 29, 61, 30, 61, 31, 61, 32, 61, 33, 61, 1, 60, 61, 10, 61, 29, 61, 30, 61, 31, 61, 32, 61, 33, 61, 37, 60, 61, 10, 61, 29, 61, 1, 61, 31, 61, 32, 61, 33, 61, 34, 60, 61, 10, 61, 29, 61, 1, 61, 31, 61, 32, 61, 33, 61, 43, 59, 61, 21, 61, 5, 61, 0, 61, 1, 61, 2, 61, 0, 61, 3, 61, 4, 58, 60, 61, 10, 61, 7, 61, 5, 61, 0, 61, 1, 61, 2, 61, 0, 61, 3, 61, 20, 59, 61, 9, 61, 5, 6

In [15]:
from text_dataset import create_data_loader

stride=12

train_data_loader = create_data_loader(token_ids, context_length, stride, batch_size=1, shuffle=False)

In [16]:
data_iter = iter(train_data_loader)

In [17]:
next(data_iter)

[tensor([[ 0, 61,  1, 61,  2, 61,  0, 61,  3, 61,  4, 58]]),
 tensor([[61,  1, 61,  2, 61,  0, 61,  3, 61,  4, 58, 61]])]

### Embedding, sözlük anlamların sayısal değerleri

In [18]:
import torch

embedding = torch.nn.Embedding(num_embeddings=64, embedding_dim=4)

In [19]:
embedding(torch.tensor(token_ids))

tensor([[-0.8253, -2.5668, -0.0428,  0.7357],
        [-0.1035,  2.2483,  0.2827,  0.8886],
        [-2.4981, -0.8064,  0.9115,  0.2118],
        ...,
        [-0.1035,  2.2483,  0.2827,  0.8886],
        [-0.9575, -0.2505, -0.0163, -1.2636],
        [-0.1534,  0.3837,  0.1191,  0.7264]], grad_fn=<EmbeddingBackward0>)

In [41]:
example = "the capital of united states"
example_tokens = tokenizer.encode("the capital of united states")
example_tokens

[0, 61, 1, 61, 2, 61, 3, 61, 4, 58]

In [42]:
example_meaning = embedding(torch.tensor(example_tokens))
example_meaning

tensor([[-0.8253, -2.5668, -0.0428,  0.7357],
        [-0.1035,  2.2483,  0.2827,  0.8886],
        [-2.4981, -0.8064,  0.9115,  0.2118],
        [-0.1035,  2.2483,  0.2827,  0.8886],
        [-0.1743,  0.3156, -0.5717,  1.1267],
        [-0.1035,  2.2483,  0.2827,  0.8886],
        [-0.2492,  0.9465,  0.2669,  0.1582],
        [-0.1035,  2.2483,  0.2827,  0.8886],
        [-0.2480,  0.3633, -1.5589, -0.1801],
        [-0.1366, -0.5643,  0.3048, -1.3452]], grad_fn=<EmbeddingBackward0>)

In [43]:
example_meaning.shape

torch.Size([10, 4])

In [23]:
import plotly.graph_objects as go
import plotly.offline

def plot_dots(sentences_data, title, dims=[0, 1, 2]):
    data = [
      go.Scatter3d(
        x=sentence_data["words"][:, dims[0]],
        y=sentence_data["words"][:, dims[1]],
        z=sentence_data["words"][:, dims[2]],
        mode="markers+text",
        marker=dict(
          size=6,
          color=sentence_data["color"],
        ),
        text=sentence_data["labels"],
        hoverinfo="text",
      ) for sentence_data in sentences_data
    ]

    layout = go.Layout(
      scene=dict(
        xaxis_title="Sertlik",
        yaxis_title="Parlaklık",
        zaxis_title="Kırmızılık",
      ),
      title=title,
    )

    fig = go.Figure(data=data, layout=layout)
    plotly.offline.iplot(fig)

In [44]:
tokenizer.tokenizer(example)

['the', ' ', 'capital', ' ', 'of', ' ', 'united', ' ', 'state', 's']

In [45]:
sentences = [
  {
    "words": example_meaning.detach().numpy(),
    "labels": tokenizer.tokenizer(example),
    "color": "red",
  },
]
plot_dots(sentences, "Sözlük V1")

In [52]:
from transformers import AutoTokenizer, AutoModelForCausalLM, Gemma3ForCausalLM

gemma_tokenizer = AutoTokenizer.from_pretrained("google/gemma-3-1b-it")
gemma_model = Gemma3ForCausalLM.from_pretrained("google/gemma-3-1b-it")

Loading weights: 100%|██████████| 340/340 [00:00<00:00, 4391.78it/s]


In [53]:
gemma_model

Gemma3ForCausalLM(
  (model): Gemma3TextModel(
    (embed_tokens): Gemma3TextScaledWordEmbedding(262144, 1152, padding_idx=0)
    (layers): ModuleList(
      (0-25): 26 x Gemma3DecoderLayer(
        (self_attn): Gemma3Attention(
          (q_proj): Linear(in_features=1152, out_features=1024, bias=False)
          (k_proj): Linear(in_features=1152, out_features=256, bias=False)
          (v_proj): Linear(in_features=1152, out_features=256, bias=False)
          (o_proj): Linear(in_features=1024, out_features=1152, bias=False)
          (q_norm): Gemma3RMSNorm((256,), eps=1e-06)
          (k_norm): Gemma3RMSNorm((256,), eps=1e-06)
        )
        (mlp): Gemma3MLP(
          (gate_proj): Linear(in_features=1152, out_features=6912, bias=False)
          (up_proj): Linear(in_features=1152, out_features=6912, bias=False)
          (down_proj): Linear(in_features=6912, out_features=1152, bias=False)
          (act_fn): GELUTanh()
        )
        (input_layernorm): Gemma3RMSNorm((1152,), e

In [54]:
gemma_model.model.embed_tokens

Gemma3TextScaledWordEmbedding(262144, 1152, padding_idx=0)

In [55]:
gemma_tokens = gemma_tokenizer.encode("the capital of united states")
gemma_tokens

[2, 1437, 5279, 529, 26974, 5022]

In [30]:
gemma_meaning = gemma_model.model.embed_tokens(torch.tensor(gemma_tokens))
gemma_meaning.shape

torch.Size([6, 1152])

In [31]:
gemma_meaning

tensor([[ 0.1387, -0.2168, -0.5391,  ..., -0.2471,  0.0267,  0.1260],
        [-0.1670,  1.2812,  0.7930,  ...,  0.6562,  1.1797, -0.4902],
        [ 0.8086,  0.4727,  0.5742,  ...,  0.5156, -0.3203, -0.2578],
        [ 0.3828,  0.2617,  0.0801,  ...,  0.0192,  0.0074,  0.5898],
        [-0.7500, -0.7422, -1.1406,  ..., -1.2734, -0.4258, -0.4961],
        [-0.8516, -0.0052,  0.2656,  ...,  0.8633, -1.8516,  0.4570]],
       dtype=torch.bfloat16, grad_fn=<MulBackward0>)

In [32]:
gemma_tokenizer.tokenize("the capital of united states")

['the', '▁capital', '▁of', '▁united', '▁states']

In [ ]:
sentences = [
  {
    "words": gemma_meaning.detach().cpu().float().numpy(),
    "labels": gemma_tokenizer.tokenize("the capital of united states"),
    "color": "red",
  },
]
plot_dots(sentences, "Gemma", dims=[20,21,22])

In [34]:
gemma_meaning.detach().cpu().float().numpy()

array([[ 0.13867188, -0.21679688, -0.5390625 , ..., -0.24707031,
         0.0267334 ,  0.12597656],
       [-0.16699219,  1.28125   ,  0.79296875, ...,  0.65625   ,
         1.1796875 , -0.49023438],
       [ 0.80859375,  0.47265625,  0.57421875, ...,  0.515625  ,
        -0.3203125 , -0.2578125 ],
       [ 0.3828125 ,  0.26171875,  0.08007812, ...,  0.01916504,
         0.00738525,  0.58984375],
       [-0.75      , -0.7421875 , -1.140625  , ..., -1.2734375 ,
        -0.42578125, -0.49609375],
       [-0.8515625 , -0.00521851,  0.265625  , ...,  0.86328125,
        -1.8515625 ,  0.45703125]], shape=(6, 1152), dtype=float32)

### cümledeki yerine göre embedding

In [35]:
depend_sentence = "the capital of united states and the capital of france"


In [46]:
depend_sentence_token_ids = tokenizer.encode("the capital of united states")
depend_sentence_tokens = tokenizer.tokenizer(depend_sentence)

In [47]:
depend_sentence_meaning = embedding(torch.tensor(depend_sentence_token_ids))

sentences = [
  {
    "words": depend_sentence_meaning.detach().numpy(),
    "labels": depend_sentence_tokens,
    "color": "red",
  },
]
plot_dots(sentences, "Depends on Sentence")

In [50]:
gemma_depend_sentence_token_ids = gemma_tokenizer.encode(depend_sentence)
gemma_depend_sentence_tokens = gemma_tokenizer.tokenize(depend_sentence)
gemma_depend_sentence_meaning = gemma_model.model.embed_tokens(torch.tensor(gemma_depend_sentence_token_ids))

In [51]:
sentences = [
  {
    "words": gemma_depend_sentence_meaning.detach().cpu().float().numpy(),
    "labels": gemma_depend_sentence_tokens,
    "color": "red",
  },
]
plot_dots(sentences, "Depends on Sentence")